name: Build and Release FileCrypt

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact: filecrypt-linux-x86_64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact: filecrypt-windows-x86_64.exe
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact: filecrypt-macos-x86_64
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact: filecrypt-macos-arm64

    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - name: Build
        run: cargo build --release --target ${{ matrix.target }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: target/${{ matrix.target }}/release/${{ matrix.artifact }}

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/filecrypt-linux-x86_64/filecrypt-linux-x86_64
            artifacts/filecrypt-windows-x86_64.exe/filecrypt-windows-x86_64.exe
            artifacts/filecrypt-macos-x86_64/filecrypt-macos-x86_64
            artifacts/filecrypt-macos-arm64/filecrypt-macos-arm64
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
